### ISSUE TITLE
asking for the PRN-Deficient fasta file

### ISSUE THREAD

**Issue by cmlbright** [noemielefrancq/GlobalPhylogeographyPertussis#4]
Dear Noémie Lefrancq,

I have read the paper (Science translational medicine. 2022;14(642):eabn3253), and have interest on the PRN-Deficient isolates. We are now analyzing several Bp isolates from China, and want to ask for the PRN-Deficient fasta file to blast our isolates. Many thanks!

**Comment by noemielefrancq** [comment]
Hi there, 
Thanks for reading our paper! I just uploaded the fasta files for the PRN alleles and the PRN deficiency events (in the Data/Alleles folder). Happy blasting!
